theme: jekyll-theme-cayman
name: "CBB7520 SP26"
title: "Biomedical Data Science: Mining and Modeling (Spring 2026)"
description: "Spring 2026"
author:
  name: Suchen Zheng
  email: suchen.zheng@yale.edu
